export interface Accounts {
  id_backup: number,
  id_account: number,
  name: string,
  detail: string,
  sign: string,
  income: number,
  expense: number,
  initial_balance: number,
  final_balance: number,
  month: number,
  year: number,
  positive_limit: number,
  negative_limit: number,
  positive_max: number,
  negative_max: number,
  iso_code: string,
  selected: number,
  value_type: number,
  include_total: number,
  rate: number,
  icon_name: string,
}
